version: "3.9"
services:
  neo4j-test:
    image: "neo4j:latest"
    volumes:
      - "$HOME/neo4j/data:/data"
      - "$HOME/neo4j/logs:/logs"
      - "$HOME/neo4j/import:/var/lib/neo4j/import"
      - "$HOME/neo4j/plugins:/plugins"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/1234
      - NEO4JLABS_PLUGINS=["graph-data-science"]
